# Generated by Django 2.0.7 on 2018-07-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_squashed_0003_auto_20170308_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='conversion_src_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recipes.Unit'),
        ),
        migrations.AlterField(
            model_name='food',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.FoodGroup'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipes.Direction'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='prep_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.PrepMethod'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.Unit'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ServingString'),
        ),
    ]
